#!/bin/sh
if [ "$(basename `pwd`)" != "planet-web" ]; then
	echo "YOU MUST RUN THIS IN planet-web!"
	exit 1
elif [ ! -f config/$1/config.ini ]; then
	echo "You must specify an existing planet to update."
	exit 1
elif [ -f lock.$1 ]; then
	# quietly exit
	exit
else
	touch lock.$1
fi

pushd config/$1 > /dev/null
#/usr/local/bin/planet/planet.py config.ini
echo $1 ... $(pwd)
popd > /dev/null

rm -f lock.$1
