#!/bin/sh
#PLANET=/usr/local/bin/planet/planet.py
#PLANET=/home/users/jdub/public_html/bzr/planet/devel/trunk/planet.py
PLANET=/var/cache/gnomeweb/venus/planet.py

if [ "$(basename `pwd`)" != "planet-web" ]; then
	echo "YOU MUST RUN THIS IN planet-web!"
	exit 1
elif [ ! -f config/$1/config.ini ]; then
	echo "You must specify an existing planet to update."
	exit 1
elif [ -f lock.$1 ]; then
	# quietly exit
	exit
else
	CONFIG=$1
	touch lock.$CONFIG
	shift
fi

# Checkout Venus (planetplanet) if we do not have it
if [ -f /var/cache/gnomeweb/venus ]; then
	pushd /var/cache/gnomeweb
	git clone https://github.com/rubys/venus
	popd > /dev/null
fi

pushd config/$CONFIG > /dev/null
nice $PLANET $@ config.ini
popd > /dev/null

rm -f lock.$CONFIG
