#!/bin/sh
(echo "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">
<html>

<head>
	<title>Hackergotchi Heads!</title>
</head>

<body style=\"background-color: #eeeeee;\">

<h1 style=\"text-align: center;\">Hackergotchi Heads!</h1>

<p>"

for i in web/heads/*.png; do
	THUMB=$(basename $i)
	if [ -f "web/heads/big/$THUMB" ]; then
		echo "<a href=\"http://planet.gnome.org/heads/big/$THUMB\">"
		echo "  <img src=\"http://planet.gnome.org/heads/$THUMB\" border=\"0\">"
		echo "</a>"
	else
		echo "<img src=\"http://planet.gnome.org/heads/$THUMB\" border=\"0\">"
	fi
done

echo "</p>

<p>Hackergotchi heads gimped up by Tuomas Kuosmanen, Jakub Steiner, Luke Stroven, Pat Suwalski, Antonio Ognio and occasionally the person who owns the head in question.</p>

<h1 style=\"text-align: center;\">Logos and Other Stuff</h1>

<p>"

for i in web/heads/logos/*.{png,jpg}; do
	THUMB=$(basename $i)
	echo "<img src=\"http://planet.gnome.org/heads/logos/$THUMB\"
		border=\"0\">"
done

echo "</p>

</body>

</html>") > web/heads/index.html

chmod +r web/heads/index.html
